//! Shared destination validation and bounded, atomic artifact writing.
//!
//! Both review bundles publish into a new directory that must not already
//! exist, write every file atomically, hash what they wrote, and stop at a
//! total byte budget. A bundle without its completion marker is explicitly
//! incomplete and is never treated as usable.

use std::{
    fs,
    io::{self, Write},
    path::Path,
};

use serde::Serialize;
use sha2::{Digest, Sha256};

/// Total bytes one bundle may publish.
pub(crate) const MAX_BYTES: usize = 512 * 1024 * 1024;

/// One published file, with the exact bytes written and their digest.
///
/// The digest identifies the artifact and detects drift. It is not a proof
/// about the document's content.
#[derive(Serialize)]
pub(crate) struct Artifact {
    pub name: String,
    pub bytes: usize,
    pub sha256: String,
}

/// Refuses a destination that already exists or collides with another output.
///
/// Publishing into an existing directory could overwrite unrelated files, and a
/// report written inside the bundle would be captured by the bundle's own
/// manifest, so both are rejected rather than merged.
pub(crate) fn validate_destination(
    directory: &Path,
    outputs: &[Option<&Path>],
) -> Result<(), String> {
    match fs::symlink_metadata(directory) {
        Ok(_) => {
            return Err(format!(
                "refusing existing review directory {}",
                directory.display()
            ));
        }
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => {
            return Err(format!(
                "cannot inspect review directory {}: {error}",
                directory.display()
            ));
        }
    }
    let destination = crate::fs::normalized_destination(directory, "review directory")?;
    for output in outputs.iter().flatten() {
        if crate::fs::normalized_destination(output, "review output")?.starts_with(&destination) {
            return Err(format!(
                "output {} collides with the review directory",
                output.display()
            ));
        }
    }
    Ok(())
}

/// Creates the bundle directory with owner-only access.
pub(crate) fn create_directory(directory: &Path) -> Result<(), String> {
    let mut builder = fs::DirBuilder::new();
    #[cfg(unix)]
    {
        use std::os::unix::fs::DirBuilderExt;
        builder.mode(0o700);
    }
    builder.create(directory).map_err(|error| {
        format!(
            "cannot create new review directory {}: {error}",
            directory.display()
        )
    })
}

pub(crate) struct BoundedWriter<'a> {
    pub inner: &'a mut dyn Write,
    pub remaining: &'a mut usize,
    pub hash: &'a mut Sha256,
}

impl Write for BoundedWriter<'_> {
    fn write(&mut self, bytes: &[u8]) -> io::Result<usize> {
        if bytes.len() > *self.remaining {
            return Err(io::Error::other(
                "review bundle exceeds its 512 MiB output budget",
            ));
        }
        self.inner.write_all(bytes)?;
        self.hash.update(bytes);
        *self.remaining -= bytes.len();
        Ok(bytes.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        self.inner.flush()
    }
}

/// Publishes one artifact atomically inside the bundle, charging the budget.
///
/// `name` is a bundle-relative path generated by this program. It is never
/// derived from document content, so no document can choose where bytes land.
pub(crate) fn file(
    directory: &Path,
    name: &str,
    remaining: &mut usize,
    write: impl FnOnce(&mut dyn Write) -> io::Result<()>,
) -> Result<Artifact, String> {
    let before = *remaining;
    let mut hash = Sha256::new();
    if let Some(parent) = Path::new(name)
        .parent()
        .filter(|path| !path.as_os_str().is_empty())
    {
        fs::create_dir_all(directory.join(parent))
            .map_err(|error| format!("cannot create review artifact directory {name}: {error}"))?;
    }
    crate::fs::write_output_atomically(&directory.join(name), "review artifact", |writer| {
        write(&mut BoundedWriter {
            inner: writer,
            remaining,
            hash: &mut hash,
        })
        .map_err(|error| format!("cannot write review artifact {name}: {error}"))
    })?;
    Ok(Artifact {
        name: name.into(),
        bytes: before - *remaining,
        sha256: crate::fs::lowercase_hex(&hash.finalize()),
    })
}

/// Writes one lossless RGB raster as a PNG.
///
/// The samples are the ones the comparison retained; nothing is resampled,
/// so a published page is the same observation the engine examined.
pub(crate) fn write_png(
    out: &mut dyn Write,
    width: u32,
    height: u32,
    rgb: &[u8],
) -> io::Result<()> {
    let mut encoder = png::Encoder::new(out, width, height);
    encoder.set_color(png::ColorType::Rgb);
    encoder.set_depth(png::BitDepth::Eight);
    let mut writer = encoder.write_header().map_err(io::Error::other)?;
    writer.write_image_data(rgb).map_err(io::Error::other)?;
    writer.finish().map_err(io::Error::other)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn output_budget_rejects_excess_without_partial_chunk_or_charge() {
        let mut output = Vec::new();
        let mut remaining = 3;
        let mut hash = Sha256::new();
        let mut writer = BoundedWriter {
            inner: &mut output,
            remaining: &mut remaining,
            hash: &mut hash,
        };
        writer.write_all(b"ab").expect("bounded prefix");
        assert!(writer.write_all(b"cd").is_err());
        assert_eq!(remaining, 1);
        assert_eq!(output, b"ab");
        assert_eq!(hash.finalize(), Sha256::digest(b"ab"));
    }
}
